### ISSUE TITLE
Great write up! Recommendations

### ISSUE THREAD

**Issue by leongersing** [schmidtsusanr/user_authentication#1]
@schmidtsusanr this is a killer write up. Well done! Feel free to close this issue when you read it; just wanted to show some :green_heart: to a great writeup.

**Comment by schmidtsusanr** [comment]
Thanks @leongersing! 

The internal README was originally an .rdoc, but I couldn't get the markdown to work so I changed it to an .md file and formatted it. Also, I've added a resources section at the bottom of it to give credit to my sources and provide resources for anyone interested in learning more about what I've implemented...you should check it out!  :smile:
